### PR TITLE
Record ReturnValue on CompletedFakeObjectCall

### LINKED ISSUE #1696: ReturnValue not set
It seems like the ReturnValue of ICompletedFakeObjectCall is not being set. This test fails:

```c#
[Fact]
public void RetrnValueIsSet()
{
    var fake = A.Fake<IInterface>();

    var returnValue = fake.Function();

    Fake.GetCalls(fake).Single().ReturnValue.ShouldBe(returnValue);
}

public interface IInterface
{
    object Function();
}
```

Am I misunderstanding something - or is this a bug? 

Using FakeItEasy version 5.4.0 on netcore 3.0.

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #1696 

~~WIP because I want to try another approach~~ Scratch that, my idea won't work...

### CODE REVIEW

File: src/FakeItEasy/Core/InterceptedFakeObjectCall.cs [hunk 1]
```diff
@@ -21,10 +21,15 @@ internal abstract class InterceptedFakeObjectCall : IInterceptedFakeObjectCall
         public abstract MethodInfo Method { get; }
 
         /// <summary>
-        /// Freezes the call so that it can no longer be modified.
+        /// Gets or sets the return value of the call.
+        /// </summary>
+        public abstract object ReturnValue { get; internal set; }
```
Comment (thomaslevesque) [inline src/FakeItEasy/Core/InterceptedFakeObjectCall.cs]: I had to choose between adding a `GetReturnValue()` method, or change to a property. The accessor method pair felt to "Javaesque" for my taste...

File: src/FakeItEasy/Core/FakeManager.cs [hunk 2]
```diff
@@ -159,18 +159,19 @@ void IFakeCallProcessor.Process(InterceptedFakeObjectCall fakeObjectCall)
                 listenerNode.Value.OnBeforeCallIntercepted(fakeObjectCall);
             }
 
-            var readonlyCall = fakeObjectCall.AsReadOnly();
-            this.RecordCall(readonlyCall);
+            var callToRecord = fakeObjectCall.ToCompletedCall();
```
Comment (thomaslevesque) [inline src/FakeItEasy/Core/FakeManager.cs]: Because it's no longer true that `CompletedFakeObjectCall` is read-only

File: src/FakeItEasy/Core/InterceptedFakeObjectCall.cs (hunk 1 above)
Comment (blairconrad) [reply src/FakeItEasy/Core/InterceptedFakeObjectCall.cs]: The class is internal, so we could just leave the set public…

Comment (thomaslevesque) [reply src/FakeItEasy/Core/InterceptedFakeObjectCall.cs]: Good point!

File: src/FakeItEasy/Core/CompletedFakeObjectCall.cs [hunk 3]
```diff
@@ -15,7 +15,7 @@ public CompletedFakeObjectCall(IInterceptedFakeObjectCall interceptedCall, objec
             this.SequenceNumber = SequenceNumberManager.GetNextSequenceNumber();
```
Comment (blairconrad) [inline src/FakeItEasy/Core/CompletedFakeObjectCall.cs]: I can't make  a comment any higher, but do we expect the `returnValue` provided in the constructor to survive? Could it be dispensed with?

File: src/FakeItEasy/Creation/CastleDynamicProxy/CastleInvocationCallAdapter.cs [hunk 4]
```diff
@@ -46,11 +46,17 @@ public CastleInvocationCallAdapter(IInvocation invocation)
...
         public override object FakedObject => this.invocation.Proxy;
 
+        public override object ReturnValue
+        {
+            get => this.invocation.ReturnValue;
+            internal set => this.invocation.ReturnValue = value;
+        }
+
         /// <summary>
         /// Freezes the call so that it can no longer be modified.
```
[the remark this answers is not in the document]
Comment (thomaslevesque) [reply src/FakeItEasy/Creation/CastleDynamicProxy/CastleInvocationCallAdapter.cs]: Oops

File: src/FakeItEasy/Core/CompletedFakeObjectCall.cs (hunk 3 above)
Comment (thomaslevesque) [reply src/FakeItEasy/Core/CompletedFakeObjectCall.cs]: Yes, I'll remove it. Thanks!

**Comment by thomaslevesque** [comment]
> I wonder if it isn't worthwhile testing a faked delegate as well?

It is!

**Comment by thomaslevesque** [comment]
> And I just thought of another thing `ICompletedFakeObjectCall.ReturnValue` has a slightly misleading comment, as I noted in the issue. Perhaps a good idea to fix up while you're here, if you'd be so kind, to indicate that it's the value that was returned, not the value _set to be returned_.

Will do

**Comment by thomaslevesque** [comment]
> Squash it up!

Done

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque!

**Comment by thomaslevesque** [comment]
Thanks for the review!
