### PR TITLE
Fix: assigning ref param overwrites recorded argument

### LINKED ISSUE #1124: Setting out or ref argument values masks incoming argument values used to verify calls
From https://github.com/FakeItEasy/FakeItEasy/issues/18#issuecomment-308478748. Discovered by @StarWars999123.

`ApplyOutAndRefParametersValueProducer` is mutating our incoming call object before we build "recorded call" out of it.

We should probably alter a copy of the arguments and use those to build the completed call.

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #1124

### CODE REVIEW

File: src/FakeItEasy/SelfInitializedFakes/SelfInitializationRule.cs [hunk 1]
```diff
@@ -55,7 +56,12 @@ public void Apply(IInterceptedFakeObjectCall fakeObjectCall)
             if (this.recorder.IsRecording)
             {
                 this.wrappedRule.Apply(fakeObjectCall);
-                this.recorder.RecordCall(fakeObjectCall.AsReadOnly());
+                var completedFakeObjectCall = new CompletedFakeObjectCall(
+                    fakeObjectCall.FakedObject,
+                    fakeObjectCall.Method,
+                    fakeObjectCall.Arguments.ToArray(),
+                    fakeObjectCall.AsReadOnly().ReturnValue);
+                this.recorder.RecordCall(completedFakeObjectCall);
```
Comment (thomaslevesque) [inline src/FakeItEasy/SelfInitializedFakes/SelfInitializationRule.cs]: The recorder expects a call that contains the post-call arguments (in order to be able to replay it with the appropriate out and ref arguments), but `AsReadOnly()` returns a call that contains the incoming arguments. So I'm explicitly creating a call that has the expected arguments. It's a little ugly, but it's not for long, since SelfInitializedFakes are being removed in 4.0.0.

btw, @blairconrad, your SelfInitializedFakes library will probably be affected by this fix as well. We could extend `ICompletedFakeObjectCall` to include both the incoming and outgoing arguments, if necessary.

File: src/FakeItEasy/Core/CompletedFakeObjectCall.cs [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+            this.Method = method;
+            this.Arguments = new ArgumentCollection(arguments, method);
+            this.ReturnValue = returnValue;
+        }
+
+        public object ReturnValue { get; }
+
+        public MethodInfo Method { get; }
+
+        public ArgumentCollection Arguments { get; }
```
Comment (blairconrad) [inline src/FakeItEasy/Core/CompletedFakeObjectCall.cs]: It's a little troubling that `Arguments` means two different things, depending on the type of the underlying object implementing `IFakeObjectCall`. I'm not sure what to do about it, though.

File: src/FakeItEasy/Core/FakeManager.cs [hunk 3]
```diff
@@ -170,6 +170,7 @@ internal IEnumerable<ICompletedFakeObjectCall> GetRecordedCalls()
         /// <param name="call">The call to remember.</param>
         internal void RecordCall(ICompletedFakeObjectCall call)
         {
+            SequenceNumberManager.RecordSequenceNumber(call);
```
Comment (blairconrad) [inline src/FakeItEasy/Core/FakeManager.cs]: This is an excellent change.

File: tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs [hunk 4]
```diff
@@ -157,5 +157,31 @@ public static void AssignOutAndRefParameters(IHaveARef subject, string outValue)
...
+            "And the configured method is called"
+                .x(() => subject.MightReturnAKnownValue(ref refValue));
+
+            "The the assertion that a call with the expected value has happened succeeds"
+                .x(() =>
+                {
+                    string expectedValue = Condition;
+                    A.CallTo(() => subject.MightReturnAKnownValue(ref expectedValue)).MustHaveHappened();
+                });
+        }
```
Comment (blairconrad) [inline tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs]: Since the delegate fakes needed an additional change, I think we should have a spec for them too.

File: src/FakeItEasy/Core/CompletedFakeObjectCall.cs (hunk 2 above)
Comment (thomaslevesque) [inline src/FakeItEasy/Core/CompletedFakeObjectCall.cs]: True. Maybe we should change the API in 4.0.0 to expose both.

File: tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs (hunk 4 above)
Comment (thomaslevesque) [inline tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs]: Good point. I'll add it.

Comment (thomaslevesque) [inline tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs]: Done

**Comment by blairconrad** [comment]
:+1:

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque!
