### PR TITLE
Wrap exception from argument constraint factory

### LINKED ISSUE #1646: Exception thrown by argument constraint factory is wrapped in TargetInvocationException, not UserCallbackException

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #1646

### CODE REVIEW

File: src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs [hunk 1]
```diff
@@ -161,9 +161,19 @@ private IArgumentConstraint GetArgumentConstraintFromExpression(Expression expre
...
+                constraint = this.argumentConstraintTrapper.TrapConstraintOrCreate(
+                    () => expressionValue = expression.Evaluate(),
+                    () => CreateEqualityConstraint(expressionValue));
+            }
+            catch (TargetInvocationException ex)
+            {
+                throw new UserCallbackException(
+                    ExceptionMessages.UserCallbackThrewAnException($"Argument constraint expression <{expression}>"),
+                    ex.InnerException);
+            }
```
Comment (thomaslevesque) [inline src/FakeItEasy/Expressions/ExpressionArgumentConstraintFactory.cs]: I removed the `TargetInvocationException` and just wrapped its `InnerException`. I don't think the TIE provides any useful information.

**Comment by thomaslevesque** [comment]
Thanks!
