### PR TITLE
Include name of the method that can't be intercepted in the error message

### LINKED ISSUE #786: In error messages, name the method that we can't intercept on an instance
Inspired by a [StackOverflow question](http://stackoverflow.com/q/38152748/1199).

The questioner had the equivalent of

``` c#
public interface IHaveAList
{
    IEnumerable<string> GetList();
}

var fake = A.Fake<IHaveAList>();
A.CallTo(() => fake.GetList().Single())
    .Throws(new Exception());
```

And didn't understand why he was told 

```
FakeItEasy.Configuration.FakeConfigurationException: 
The current proxy generator can not intercept the specified method for the following reason: 
- Extension methods can not be intercepted since they're static.
```

The thought was the complaint was about `GetList`, when really it was about `Single`.

We should say which method (I'd almost hope for something like `Enumerable.Single<TSource>(this IEnumerable<TSource> source)`, but whatever we can get would be great.
We could maybe take a cue from `DefaultFakeObjectCallFormatter`, which has very advanced formatting rules based on whether the method is a method or a property and so on, but it's concerned with object calls and we only have `MethodInfo`s available where we build the exception message above (in `DefaultInterceptionAsserter.AssertThatMethodCanBeInterceptedOnInstance`), so we'd need to do a little work for  a full-fidelity solution.

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #786

### CODE REVIEW

File: src/FakeItEasy/Core/DefaultFakeObjectCallFormatter.cs [hunk 1]
```diff
@@ -90,21 +88,6 @@ private static void AppendMethodName(StringBuilder builder, MethodInfo method)
...
-
-        private static bool IsPropertySetter(MethodInfo method)
-        {
-            return method.IsSpecialName && method.Name.StartsWith("set_", StringComparison.Ordinal);
-        }
-
-        private static bool IsPropertyGetter(MethodInfo method)
-        {
-            return method.IsSpecialName && method.Name.StartsWith("get_", StringComparison.Ordinal);
-        }
```
Comment (thomaslevesque) [inline src/FakeItEasy/Core/DefaultFakeObjectCallFormatter.cs]: Promoted to extension methods

File: src/FakeItEasy/MethodBaseExtensions.cs [hunk 2]
```diff
@@ -18,5 +20,119 @@ public static string GetGenericArgumentsCSharp(this MethodBase method)
...
+                builder.AppendLine();
+                builder.Append("    ");
+                return;
+            }
+
+            if (argumentIndex > 0)
+            {
+                builder.Append(", ");
+            }
+        }
```
Comment (thomaslevesque) [inline src/FakeItEasy/MethodBaseExtensions.cs]: I'm not very happy about this... it's mostly the same code as in `DefaultFakeObjectCallFormatter`, with a few small differences. I considered putting the new `GetDescription` method in `IFakeObjectCallFormatter` to take advantage of the existing code, but it didn't feel right.

File: src/FakeItEasy/MethodBaseExtensions.cs [hunk 3]
```diff
@@ -18,5 +20,119 @@ public static string GetGenericArgumentsCSharp(this MethodBase method)
...
+            if (IsPropertyGetterOrSetter(method))
+            {
+                builder.Append(method.Name.Substring(4));
+            }
+            else
+            {
+                builder.Append(method.Name);
+            }
+
+            builder.Append(method.GetGenericArgumentsCSharp());
```
Comment (thomaslevesque) [inline src/FakeItEasy/MethodBaseExtensions.cs]: For consistency with how calls are formatted. Will need to be changed as part of #1047

File: src/FakeItEasy/MethodBaseExtensions.cs [hunk 4]
```diff
@@ -18,5 +20,119 @@ public static string GetGenericArgumentsCSharp(this MethodBase method)
...
+            }
+        }
+
+        private static void AppendParameters(StringBuilder builder, ParameterInfo[] parameters)
+        {
+            for (int i = 0; i < parameters.Length; i++)
+            {
+                AppendParameterSeparator(builder, i, parameters.Length);
+                builder
+                    .Append(parameters[i].ParameterType.FullNameCSharp())
```
Comment (thomaslevesque) [inline src/FakeItEasy/MethodBaseExtensions.cs]: For consistency with how calls are formatted. Will need to be changed as part of #1047

File: src/FakeItEasy/MethodBaseExtensions.cs (hunk 2 above)
Comment (blairconrad) [inline src/FakeItEasy/MethodBaseExtensions.cs]: I see what you're saying.
I'm not super bothered by the duplication.

Of course, I didn't notice any tests that cover the 3+ parameter case (which I fear might look funny when it's rendered...)

Comment (blairconrad) [inline src/FakeItEasy/MethodBaseExtensions.cs]: Nor do I see property-covering tests, now that I think about it.

**Comment by blairconrad** [comment]
Looks quite good, @thomaslevesque, other than my fears about rendering long calls.

File: src/FakeItEasy/MethodBaseExtensions.cs (hunk 2 above)
Comment (thomaslevesque) [inline src/FakeItEasy/MethodBaseExtensions.cs]: Good point, I'll add some tests.

Comment (thomaslevesque) [inline src/FakeItEasy/MethodBaseExtensions.cs]: We probably don't want to split on multiple lines in this scenario. Should I add a parameter to control this? Or just assume we never want to split on multiple lines?

Comment (blairconrad) [inline src/FakeItEasy/MethodBaseExtensions.cs]: Until we need different behaviour, I would just assume we don't want to split.

File: src/FakeItEasy/MethodBaseExtensions.cs [hunk 5]
```diff
@@ -18,5 +20,119 @@ public static string GetGenericArgumentsCSharp(this MethodBase method)
...
+        {
+            return method.IsSpecialName && method.Name.StartsWith("get_", StringComparison.Ordinal);
+        }
+
+        public static string GetDescription(this MethodBase method)
+        {
+            var builder = new StringBuilder();
+
+            builder
+                .Append(method.DeclaringType)
```
Comment (thomaslevesque) [inline src/FakeItEasy/MethodBaseExtensions.cs]: Just noticed that we don't include "nicely formatted" generic arguments for the declaring type in `DefaultFakeObjectCallFormatter`, so the result is a mix of CLR and C# formatting. It will go away with #1047, but in the meantime, I'll fix it both in `DefaultFakeObjectCallFormatter` and here.

**Comment by thomaslevesque** [comment]
I squashed

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque!
