### PR TITLE
Handle case where some types can't be loaded from external assembly

### LINKED ISSUE #1092: Improve handling of ReflectionTypeLoadException in TypeCatalogue
Currently, if we get an error when scanning an assembly for extension points, we just emit a warning and dismiss the entire assembly. However, the error is often a `ReflectionTypeLoadException`, which gives us the option to be a little smarter:
- this exception exposes a `Types` property which is a list of types that were successfully loaded, so we could still scan those types (no need to dismiss the entire assembly just because one or two types couldn't be loaded)
- it also exposes a `LoaderExceptions` property with the errors that occurred when loading each type, so we could list the types that failed to load (and possibly indicate why they failed to load)

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #1092 

The warning message looks like this:

```
Warning: FakeItEasy failed to get some types from assembly 'FakeItEasy.ExtensionPoints.External, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' while scanning for extension points. Some IArgumentValueFormatters, IDummyFactories, and IFakeOptionsBuilders in that assembly might not be available.
  System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  1 type(s) were not loaded for the following reasons:
   - System.IO.FileNotFoundException: Could not load file or assembly 'FakeItEasy.ExtensionPoints.ExternalDependency, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
```

Unfortunately it's not always possible to get the information about *which* types can't be loaded. The information is only present if the exception is a `TypeLoadException`.

### CODE REVIEW

File: src/FakeItEasy/Core/TypeCatalogue.cs [hunk 1]
```diff
@@ -50,10 +50,20 @@ public void Load(IEnumerable<string> extraAssemblyFiles)
...
+                    {
+                        this.availableTypes.Add(type);
+                    }
+
+                    WarnFailedToGetSomeTypes(assembly, ex);
+                }
                 catch (Exception ex)
                 {
                     WarnFailedToGetTypes(assembly, ex);
-                    continue;
```
Comment (thomaslevesque) [inline src/FakeItEasy/Core/TypeCatalogue.cs]: redundant

File: src/FakeItEasy/Core/TypeCatalogue.cs [hunk 2]
```diff
@@ -73,8 +83,6 @@ private static IEnumerable<Assembly> GetAllAssemblies(IEnumerable<string> extraA
 #if FEATURE_REFLECTION_GETASSEMBLIES
             var loadedAssemblies = AppDomain.CurrentDomain.GetAssemblies();
 #else
-            var fakeItEasyLibraryName = TypeCatalogue.FakeItEasyAssembly.GetName().Name;
-
```
Comment (thomaslevesque) [inline src/FakeItEasy/Core/TypeCatalogue.cs]: never used

File: src/FakeItEasy/Core/TypeCatalogue.cs [hunk 3]
```diff
@@ -107,7 +115,7 @@ private static IEnumerable<Assembly> GetAssemblies(IEnumerable<string> files)
         {
             foreach (var file in files)
             {
-                Assembly assembly = null;
```
Comment (thomaslevesque) [inline src/FakeItEasy/Core/TypeCatalogue.cs]: redundant

File: src/FakeItEasy/Core/TypeCatalogue.cs [hunk 4]
```diff
@@ -148,28 +156,54 @@ private static void WarnFailedToLoadAssembly(string path, Exception ex)
...
+        private static void Write(Exception ex, string message, Action<IOutputWriter> additionalOutput = null)
         {
             var writer = new DefaultOutputWriter(Console.Write);
-            writer.Write(messageFormat, messageArgs);
+            writer.Write(message);
             writer.WriteLine();
             using (writer.Indent())
             {
+                writer.Write(ex.GetType());
+                writer.Write(": ");
```
Comment (thomaslevesque) [inline src/FakeItEasy/Core/TypeCatalogue.cs]: Added this because it makes it easier to understand what the problem is. The exception type is often as useful as the message. I did it in a separate commit in case we don't want it.

File: src/FakeItEasy/Core/TypeCatalogue.cs [hunk 5]
```diff
@@ -148,28 +156,54 @@ private static void WarnFailedToLoadAssembly(string path, Exception ex)
...
+                            writer.Write(loaderException.GetType());
+                            writer.Write(": ");
+                            writer.Write(loaderException.Message);
+                            writer.WriteLine();
+                        }
+                    }
+                });
+        }
+
+        private static void Write(Exception ex, string message, Action<IOutputWriter> additionalOutput = null)
```
Comment (thomaslevesque) [inline src/FakeItEasy/Core/TypeCatalogue.cs]: The delegate parameter might not be the best way to do it... If you prefer, I could return the writer instead.

File: tests/FakeItEasy.IntegrationTests/ExternalAssemblyGenerator.cs [hunk 6]
```diff
@@ -27,10 +29,16 @@ public ExternalAssemblyGenerator()
 
         /// <summary>
         /// Gets the path to a copy of <see cref="AssemblyOriginalPath"/>.
-        ///
+        /// </summary>
```
Comment (thomaslevesque) [inline tests/FakeItEasy.IntegrationTests/ExternalAssemblyGenerator.cs]: I missed this during the review of #1095...

File: tests/FakeItEasy.IntegrationTests/ExternalAssemblyGenerator.cs [hunk 7]
```diff
@@ -27,10 +29,16 @@ public ExternalAssemblyGenerator()
...
         public string AssemblyCopyPath { get; }
 
+        /// <summary>
+        /// Gets the path of an assembly on which a type of FakeItEasy.IntegrationTests.External depends.
+        /// </summary>
+        public string AssemblyDependencyPath { get; }
+
         private const string AssemblyName = "FakeItEasy.ExtensionPoints.External";
+        private const string DependencyAssemblyName = "FakeItEasy.ExtensionPoints.ExternalDependency";
```
Comment (thomaslevesque) [inline tests/FakeItEasy.IntegrationTests/ExternalAssemblyGenerator.cs]: This assembly is referenced by `FakeItEasy.ExtensionPoints.External`, but won't be available at run time. This is done in order to cause a type load error when we scan the types in `FakeItEasy.ExtensionPoints.External`.

File: tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs [hunk 8]
```diff
@@ -127,6 +127,20 @@ public void Should_not_be_able_to_get_types_from_assembly_that_does_not_referenc
...
+        {
+            // Arrange
+            var catalogue = new TypeCatalogue();
+
+            // Act
+            string output = CaptureConsoleOutput(
+                () => catalogue.Load(new[] { this.externalAssemblyGenerator.AssemblyOriginalPath }));
+
+            // Assert
+            output.Should().Match("*Warning: FakeItEasy failed to get some types from assembly 'FakeItEasy.ExtensionPoints.External*' while scanning for extension points. Some IArgumentValueFormatters, IDummyFactories, and IFakeOptionsBuilders in that assembly might not be available.*");
```
Comment (blairconrad) [inline tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs]: Perhaps we should verify the rest of the message: make sure there was 1 type not found, and that it was named?

File: src/FakeItEasy/Core/TypeCatalogue.cs (hunk 4 above)
Comment (blairconrad) [inline src/FakeItEasy/Core/TypeCatalogue.cs]: I like it.

File: src/FakeItEasy/Core/TypeCatalogue.cs (hunk 5 above)
Comment (blairconrad) [inline src/FakeItEasy/Core/TypeCatalogue.cs]: Both feel a little awkward to me.
Would you think it terrible to pass the writer in? e.g.

```c#
var writer = new DefaultOutputWriter(Console.Write);
WriteError(writer, message, ex);
```

in two places, and just above follow it up with

```
using (writer.Indent())
{
    writer.Write($"{notLoadedCount} type(s) were not loaded for the following reasons:");
    writer.WriteLine();
    foreach (var loaderException in ex.LoaderExceptions)
    {
        writer.Write(" - ");
        writer.Write(loaderException.GetType());
        writer.Write(": ");
        writer.Write(loaderException.Message);
        writer.WriteLine();
    }
}
```

?

If that doesn't appeal, I think returning the writer is a little better than the delegate.

File: tests/FakeItEasy.IntegrationTests/ExternalAssemblyGenerator.cs (hunk 7 above)
Comment (thomaslevesque) [inline tests/FakeItEasy.IntegrationTests/ExternalAssemblyGenerator.cs]: Agreed

File: tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs (hunk 8 above)
Comment (thomaslevesque) [inline tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs]: Ah, but it's *not* named in this case... The exception doesn't contain that information. The errors related to types in `DynamicProxyGenAssembly2` did contain the type name, because they were `TypeLoadException`s. In this case it's a `FileNotFoundException`.

Comment (thomaslevesque) [inline tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs]: But I can still check the rest of the message if you thing it's useful.

File: src/FakeItEasy/Core/TypeCatalogue.cs (hunk 5 above)
Comment (thomaslevesque) [inline src/FakeItEasy/Core/TypeCatalogue.cs]: In fact, we could even have a single `IOutputWriter` for the lifetime of the class. It would make things simpler.

File: tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs [hunk 9]
```diff
@@ -131,6 +131,23 @@ public void Should_not_be_able_to_get_types_from_assembly_that_does_not_referenc
...
+
+            // Act
+            string output = CaptureConsoleOutput(
+                () => catalogue.Load(new[] { this.externalAssemblyGenerator.AssemblyOriginalPath }));
+
+            // Assert
+            output.Should().Match(@"*Warning: FakeItEasy failed to get some types from assembly 'FakeItEasy.ExtensionPoints.External, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' while scanning for extension points. Some IArgumentValueFormatters, IDummyFactories, and IFakeOptionsBuilders in that assembly might not be available.
+  System.Reflection.ReflectionTypeLoadException: *.
+  1 type(s) were not loaded for the following reasons:
+   - System.IO.FileNotFoundException: *");
```
Comment (thomaslevesque) [inline tests/FakeItEasy.IntegrationTests/TypeCatalogueTests.cs]: Using wildcards instead of the actual exception messages, so that it still works on non-English systems.

**Comment by thomaslevesque** [comment]
Thanks for the review!
