### PR TITLE
Remove SelfInitializedFakes

### LINKED ISSUE #798: Remove SelfInitializedFakes from the API
The feature
1. is probably not used much
2. is [barely documented](http://fakeiteasy.readthedocs.io/en/stable/creating-fakes/#explicit-creation-options)
3. supports a very restrictive use case - the fake matches calls only on signature
4. can't record calls that throw exceptions
5. requires serialization of method info (not too hard) and out/return values (which may not be available in .NET Core, depending on the types)
6. is [causing angst](https://github.com/FakeItEasy/FakeItEasy/pull/617/files/9ea652d2bc590f081f954c9974aff6171111ef74#r69927243) over in #617.

Ditch it?

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #798

### CODE REVIEW

File: src/FakeItEasy/Core/FakeWrapperConfigurator.cs [hunk 1]
```diff
@@ -1,30 +1,18 @@
...
     using FakeItEasy.Creation;
-#if FEATURE_SELF_INITIALIZED_FAKES
-    using FakeItEasy.SelfInitializedFakes;
-#endif
 
     /// <summary>
     /// Handles configuring of fake objects to delegate all their calls to a wrapped instance.
     /// </summary>
     /// <typeparam name="T">The type of fake object generated.</typeparam>
     internal class FakeWrapperConfigurator<T>
```
Comment (blairconrad) [inline src/FakeItEasy/Core/FakeWrapperConfigurator.cs]: This class got quite thin all of a sudden. Consider removing it and making `DefaultFakeAndDummyManager` do all the work? Like so:

```diff
diff --git a/src/FakeItEasy/Creation/DefaultFakeAndDummyManager.cs b/src/FakeItEasy/Creation/DefaultFakeAndDummyManager.cs
index 73fca73..0a6ebec 100644
--- a/src/FakeItEasy/Creation/DefaultFakeAndDummyManager.cs
+++ b/src/FakeItEasy/Creation/DefaultFakeAndDummyManager.cs
@@ -100,9 +100,8 @@
            public override IFakeOptions<T> Wrapping(T wrappedInstance)
             {
                 Guard.AgainstNull(wrappedInstance, nameof(wrappedInstance));
 
-                var wrapper = new FakeWrapperConfigurator<T>(this, wrappedInstance);
-                this.ConfigureFake(fake => wrapper.ConfigureFakeToWrap(fake));
-                return wrapper;
+                this.ConfigureFake(fake => ConfigureFakeToWrap(fake, wrappedInstance));
+                return this;
             }
 
             public override IFakeOptions<T> Implements(Type interfaceType)
@@ -116,6 +115,11 @@
                 this.proxyOptions.AddProxyConfigurationAction(proxy => action((T)proxy));
                 return this;
             }

+            private static void ConfigureFakeToWrap(object fakedObject, object wrappedObject)
+            {
+                var fake = Fake.GetFakeManager(fakedObject);
+                fake.AddRuleFirst(new WrappedObjectRule(wrappedObject));
+            }
         }
     }
 }
```

(or similar)? In theory, then `FakeOptionsBase<T>` could be inlined after that, but maybe I'm being too aggressive.

File: src/FakeItEasy/FakeItEasy.csproj [hunk 2]
```diff
@@ -36,7 +36,6 @@
   </PropertyGroup>
 
   <ItemGroup Condition="'$(TargetFramework)' == 'netstandard1.6'">
-    <Compile Remove="SelfInitializedFakes/**" />
     <Compile Remove="Recorders.cs" />
     <Compile Remove="Creation/IFakeOptionsForWrappers.cs" />
     <Compile Remove="Creation/IFakeOptionsForWrappers.of.T.cs" />
```
Comment (blairconrad) [inline src/FakeItEasy/FakeItEasy.csproj]: Can the three previous lines not also be removed? I guess that would mean the whole `ItemGroup`.

File: src/FakeItEasy/SelfInitializedFakes/RecordingManager.cs [hunk 3]
```diff
@@ -1,165 +0,0 @@
...
-            {
-                call.SetArgumentValue(outputArgument.Index, outputArgument.Value);
-            }
-        }
-
-        private static void AssertThatMethodsMatches(IInterceptedFakeObjectCall call, CallDataMetadata callToApply)
-        {
-            if (!callToApply.RecordedCall.Method.Equals(call.Method))
-            {
-                throw new RecordingException(ExceptionMessages.MethodMissmatchWhenPlayingBackRecording);
```
Comment (blairconrad) [inline src/FakeItEasy/SelfInitializedFakes/RecordingManager.cs]: I think this, and a few other, `ExceptionMessages` members can be removed.

**Comment by thomaslevesque** [comment]
Sorry about that

File: src/FakeItEasy/Core/FakeWrapperConfigurator.cs (hunk 1 above)
Comment (thomaslevesque) [inline src/FakeItEasy/Core/FakeWrapperConfigurator.cs]: 👍 

This will also make the whole thing much easier to understand

File: src/FakeItEasy/FakeItEasy.csproj (hunk 2 above)
Comment (thomaslevesque) [inline src/FakeItEasy/FakeItEasy.csproj]: Ah, yes. Don't know how I missed them.

File: src/FakeItEasy/SelfInitializedFakes/RecordingManager.cs (hunk 3 above)
Comment (thomaslevesque) [inline src/FakeItEasy/SelfInitializedFakes/RecordingManager.cs]: Well spotted

**Comment by blairconrad** [comment]
Very pretty. Squash 'er up, M. Levesque!

**Comment by blairconrad** [comment]
Thank you, sir!
