### PR TITLE
Detect fake loops

### LINKED ISSUE #1603: Stack overflow exception when creating second Fake of type that takes a parameter of its own type
We are facing an issue while running the following tests:

```c#
using System;
using FakeItEasy;
using NUnit.Framework;

namespace ConsoleApp1
{
    [TestFixture]
    public class ClassTest
    {
        [SetUp]
        public void SetUp()
        {
        }

        [Test]
        public void Test1()
        {
            var fake = A.Fake<Class>();
        }

        [Test]
        public void Test2()
        {
            var fake = A.Fake<Class>();
        }
    }
    
    public class Class
    {
        public Class(Type type)
        {
        }

        public Class(Type type, Class @class)
        {
        }
    }
}
```

Only when they are executed together, the second test (Test2) fails with a Stack Overflow Exception. The first test instead has no problem. Until version 4.6.0 of FakeItEasy this sample works correctly.

### PR DESCRIPTION
**Pull request by blairconrad**
Fixes #1603.

### CODE REVIEW

**Comment by blairconrad** [comment]
It probably makes sense to squash all the commits before merge, but I left them separate for now in case they help the diffing.
General approach is pretty much what you'd expect: carry a context object everywhere, holding the current set of types being resolved.
As discussed, where the `DummyValueResolver` records that we're making a Dummy of a given type, it calls a special method on the `FakeObjectCreator` that will not immediately check that we're not resolving that same type.

File: src/FakeItEasy/Creation/LoopDetectingResolutionContext.cs [hunk 1]
```diff
@@ -0,0 +1,29 @@
+namespace FakeItEasy.Creation
+{
+    using System;
+    using System.Collections.Generic;
+
+    internal class LoopDetectingResolutionContext
```
[the remark this answers is not in the document]
Comment (thomaslevesque) [reply src/FakeItEasy/Creation/LoopDetectingResolutionContext.cs]: I think it's fine

File: src/FakeItEasy/Fake.of.T.cs [hunk 2]
```diff
@@ -21,7 +21,7 @@ public class Fake<T> : IHideObjectMembers where T : class
         /// </summary>
         public Fake()
         {
-            this.FakedObject = (T)FakeAndDummyManager.CreateFake(typeof(T), null);
+            this.FakedObject = (T)FakeAndDummyManager.CreateFake(typeof(T), null, new LoopDetectingResolutionContext());
```
Comment (thomaslevesque) [inline src/FakeItEasy/Fake.of.T.cs]: Not related to your change, but is there a reason why we don't use the `CreateFake` method as in the other constructor?

File: src/FakeItEasy/Creation/FakeObjectCreator.cs [hunk 3]
```diff
@@ -29,6 +29,30 @@ internal class FakeObjectCreator : IFakeObjectCreator, IMethodInterceptionValida
...
+                resolutionContext);
+            if (result.WasSuccessful)
+            {
+                resolutionContext.OnSuccessfulResolve(typeOfFake);
+            }
+
+            return result;
+        }
+
+        public CreationResult CreateFakeWithoutCheckingIfWeAlreadyAre(
```
Comment (thomaslevesque) [inline src/FakeItEasy/Creation/FakeObjectCreator.cs]: The name is a bit of a mouthful... Maybe `CreateFakeWithoutLoopDetection`?

File: src/FakeItEasy/Creation/DummyValueResolver.cs [hunk 4]
```diff
@@ -102,10 +102,16 @@ public ResolveByCreatingFakeStrategy(IFakeObjectCreator fakeCreator)
...
-                this.FakeCreator.CreateFake(typeOfDummy, new ProxyOptions(), resolver, resolutionContext);
+                Type typeOfDummy,
+                IDummyValueResolver resolver,
+                LoopDetectingResolutionContext resolutionContext)
+            {
+                return this.FakeCreator.CreateFakeWithoutCheckingIfWeAlreadyAre(
+                    typeOfDummy,
+                    new ProxyOptions(),
+                    resolver,
+                    resolutionContext);
```
Comment (thomaslevesque) [inline src/FakeItEasy/Creation/DummyValueResolver.cs]: I think I might be missing the whole point of this method. Why is it safe in this case to not check if we're already resolving `typeOfDummy`?

File: src/FakeItEasy/Fake.of.T.cs (hunk 2 above)
Comment (thomaslevesque) [reply src/FakeItEasy/Fake.of.T.cs]: We could just pass an options builder that does nothing... Anyway, it's off topic for this PR

File: src/FakeItEasy/Creation/FakeObjectCreator.cs (hunk 3 above)
Comment (thomaslevesque) [reply src/FakeItEasy/Creation/FakeObjectCreator.cs]: I think the doc comments are clear enough. Since it's not public anyway, I think it's OK to rely on them.

File: src/FakeItEasy/Creation/DummyValueResolver.cs (hunk 4 above)
Comment (thomaslevesque) [reply src/FakeItEasy/Creation/DummyValueResolver.cs]: Ah, I see. Thanks for the explanation.

**Comment by blairconrad** [comment]
Oh, thanks for the review and merge, @thomaslevesque! I'd meant to monitor the build and hoot you when it was done.
