### PR TITLE
Better description for IsSameSequenceAs constraint

### LINKED ISSUE #1193: Enhance formatting of received array (or enumerable?) arguments in "unmatched call" output
I'm using FIE 2.3.0

I notice it's a little hard to figure out why my test failed with the current error messages. I am doing an assertion like this:

```
            A.CallTo(() => fake.CreateNewPortRules(
                A<IList<int>>.That.IsSameSequenceAs(new[] { 987, 123 }), 
                true))
            .MustHaveHappened();
```

And the output of the failed test is this:

```
Message: FakeItEasy.ExpectationException : 

  Assertion failed for the following call:
    RedisLaunch.PortManager.CreateNewPortRules(<specified sequence>, True)
  Expected to find it at least once but found it #0 times among the calls:
    1: RedisLaunch.PortManager.SSLPorts
    2: RedisLaunch.PortManager.CreateNewPortRules(ports: System.Int32[], allow: True)
    3: RedisLaunch.PortManager.ClearTextPorts
    4: RedisLaunch.PortManager.CreateNewPortRules(ports: System.Int32[], allow: True)
    5: RedisLaunch.PortManager.CreateStartupFirewallSettings(clearTextOpen: True, sslOpen: True)
```

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #1193 

It seems to work pretty well, but I'm worried about one thing: when formatting argument values in the list of calls, what should happen for nested collections? My current implementation will recursively format the collections, but it will probably hurt the readability of the output...

Also, I noticed a few inconsistencies:
- When we write constraint descriptions, we use `IOutputWriter.WriteArgumentValue` to format values, but when we write the list of calls, we use `ArgumentValueFormatter`.
- Anyway, shouldn't `DefaultOutputWriter.WriteArgumentValue` use `ArgumentValueFormatter`, in order to take custom argument value formatters into account?
- Null values are formatted inconsistently between `DefaultOutputWriter` (`NULL`) and `ArgumentValueFormatter` (`<NULL>`).

### CODE REVIEW

File: src/FakeItEasy/OutputWriterExtensions.cs [hunk 1]
```diff
@@ -49,5 +51,72 @@ public static IOutputWriter Write(this IOutputWriter writer, object value)
...
+            var list = values.AsList();
+            if (list.Count <= maxNumber)
+            {
+                writer.WriteArgumentValues(list, separator, skipFormatting);
+            }
+            else
+            {
+                writer.WriteArgumentValues(list.Take(maxNumber - 1), separator, skipFormatting);
+                int remainingCount = list.Count - maxNumber + 1;
+                writer.Write($", ... ({remainingCount} more elements)");
```
[the remark this answers is not in the document]
Comment (thomaslevesque) [reply src/FakeItEasy/OutputWriterExtensions.cs]: > Should `,` not be the passed-in separator?

Yes. Although I doubt we'll ever use anything other than `,`... we could probably remove the parameter and hard-code it instead.

> Perhaps we could print all the elements if less than six, otherwise the first two and last two?

👍

File: tests/FakeItEasy.Tests/Core/ArgumentValueFormatterTests.cs [hunk 2]
```diff
@@ -153,7 +153,7 @@ public void Built_in_formatters_should_have_lower_than_default_priority()
             // Arrange
             var allArgumentValueFormatters = typeof(A).GetTypeInformation().Assembly.GetTypes()
                 .Where(t => t.CanBeInstantiatedAs(typeof(IArgumentValueFormatter)))
-                .Select(Activator.CreateInstance)
+                .Select(t => Activator.CreateInstance(t, GetDefaultArgumentsForConstructor(t)))
```
[the remark this answers is not in the document]
Comment (thomaslevesque) [reply tests/FakeItEasy.Tests/Core/ArgumentValueFormatterTests.cs]: Good point. It would certainly make things simpler.

File: src/FakeItEasy/OutputWriterExtensions.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (blairconrad) [reply src/FakeItEasy/OutputWriterExtensions.cs]: I think removing the parameter is a good plan.

[the remark this answers is not in the document]
Comment (thomaslevesque) [reply src/FakeItEasy/OutputWriterExtensions.cs]: While I was at it, I also removed the `maxNumber` parameter.

**Comment by thomaslevesque** [comment]
I made the requested changes, but I gave up on making fixup commits, because it was too difficult to squash cleanly...

File: src/FakeItEasy/OutputWriterExtensions.cs [hunk 3]
```diff
@@ -49,5 +51,70 @@ public static IOutputWriter Write(this IOutputWriter writer, object value)
             writer.Write(value.ToString());
             return writer;
         }
+
+        /// <summary>
+        /// Formats the specified argument values as strings and writes
+        /// them to the output, separated by the specified separator.
```
Comment (blairconrad) [inline src/FakeItEasy/OutputWriterExtensions.cs]: always a comma

File: src/FakeItEasy/OutputWriterExtensions.cs [hunk 4]
```diff
@@ -49,5 +51,70 @@ public static IOutputWriter Write(this IOutputWriter writer, object value)
...
+                writer.Write($", … ({remainingCount} more elements) …, ");
+                writer.WriteArgumentValuesImpl(list.Skip(list.Count - 2), skipFormatting);
+            }
+
+            return writer;
+        }
+
+        /// <summary>
+        /// Formats the specified argument values as strings and writes
+        /// them to the output, separated by the specified separator.
```
Comment (blairconrad) [inline src/FakeItEasy/OutputWriterExtensions.cs]: comma

File: src/FakeItEasy/OutputWriterExtensions.cs [hunk 5]
```diff
@@ -49,5 +51,70 @@ public static IOutputWriter Write(this IOutputWriter writer, object value)
...
+        /// </summary>
+        /// <param name="writer">The writer to write to.</param>
+        /// <param name="values">The values to write to the writer.</param>
+        /// <param name="skipFormatting">Specify that argument values should not be formatted.</param>
+        /// <returns>The writer.</returns>
+        private static IOutputWriter WriteArgumentValuesImpl(this IOutputWriter writer, IEnumerable values, bool skipFormatting = false)
+        {
+            Guard.AgainstNull(writer, nameof(writer));
+            Guard.AgainstNull(values, nameof(values));
```
Comment (blairconrad) [inline src/FakeItEasy/OutputWriterExtensions.cs]: Are the guards necessary for a private method (I often wonder the same thing about the internal methods as well).

File: src/FakeItEasy/OutputWriterExtensions.cs (hunk 3 above)
Comment (thomaslevesque) [reply src/FakeItEasy/OutputWriterExtensions.cs]: oops

File: src/FakeItEasy/OutputWriterExtensions.cs (hunk 5 above)
Comment (thomaslevesque) [reply src/FakeItEasy/OutputWriterExtensions.cs]: No, probably not. I'll remove them.
The way I see it, the guards are necessary for public methods to ensure the caller is using the method correctly. Internally, we're supposed to know how to use it, so if we pass a null, it's our own problem, and there's no point in throwing a specific exception. I haven't always applied this rule, though...

**Comment by thomaslevesque** [comment]
I just amended the last commit, since the changes were trivial.

**Comment by thomaslevesque** [comment]
Squashed

**Comment by blairconrad** [comment]
Thanks, @thomaslevesque!
