### PR TITLE
Fix AssignsOutAndRefParameters for faked delegates

### LINKED ISSUE #677: AssignsOutAndRefParameters on delegate proxies
Inspired by https://twitter.com/th0maswe1ss/status/723799176941699072.

`AssignsOutAndRefParameters` appears not to work for faked delegates.
[`FakeItEasy.Tests.Creation.DelegateProxies.DelegateProxyGeneratorTests.Should_return_proxy_where_out_parameter_can_be_set`](https://github.com/FakeItEasy/FakeItEasy/blob/126d6056334227cda86eeded31df36b60378cf70/tests/FakeItEasy.Tests/Creation/DelegateProxies/DelegateProxyGeneratorTests.cs#L154) has been `Ignore`d since the project came to GitHub.

If there's a way to enable assigning of out and ref parameters for faked delegates, I think we should do it.
If not, we should document the lack and provide an error when it's attempted.

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #677

WIP because I still need to add specs

I took into account the other remarks from https://github.com/thomaslevesque/FakeItEasy/commit/5570756fa1dbefc872804ad7a80bf3ad87aa9f5d

### CODE REVIEW

File: src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs [hunk 1]
```diff
@@ -74,21 +74,88 @@ private static Delegate CreateDelegateProxy(Type typeOfProxy, MethodInfo invokeM
...
+             *
+             * int ProxyFoo(int x, ref int y, out int z)
+             * {
+             *     var arguments = new[]{ (object)x, (object)y, (object)z };
+             *     var result = (int)eventRaiser.Raise(arguments);
+             *     y = (int)arguments[1];
+             *     z = (int)arguments[2];
+             *     return result;
+             * }
+             ********************************************************************/
```
Comment (blairconrad) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: A matter of style, I think, but I found the lines of `****` jarring. I think omitting them and using regular single-line comments (`//`) would be (slightly) better.
This is a very minor comment!

However, the content is very clear and really aids my understanding of the following code.

File: src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs [hunk 2]
```diff
@@ -74,21 +74,88 @@ private static Delegate CreateDelegateProxy(Type typeOfProxy, MethodInfo invokeM
...
+
+            bool isVoid = delegateMethod.ReturnType == typeof(void);
+
+            // Local variables of the generated method
+            var arguments = Expression.Variable(typeof(object[]), "arguments");
+            var result = isVoid ? null : Expression.Variable(delegateMethod.ReturnType, "result");
+
+            var bodyExpressions = new List<Expression>();
+
+            // arguments = new[]{ (object)x, (object)y, (object)z };
```
Comment (blairconrad) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: I'm not sure this adds much over the comment above. But if we think it's necessary, this is an example of where I'd introduce a method rather than a comment, such as

```c#
var arrayInit = WrapArgumentsInObjectArray(parameterExpressions);
```

Comment (blairconrad) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: Similarly almost every time there's a comment below.

File: src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs [hunk 3]
```diff
@@ -74,21 +74,88 @@ private static Delegate CreateDelegateProxy(Type typeOfProxy, MethodInfo invokeM
...
                 Expression.Constant(eventRaiser),
                 DelegateCallInterceptedEventRaiser.RaiseMethod,
-                new Expression[] { Expression.NewArrayInit(typeof(object), parameterExpressionsCastToObject) });
+                arguments);
+
+            if (!isVoid)
+            {
+                // If the return type is non void, cast the result of eventRaiser.Raise()
+                // to the real return type
+                call = Expression.Convert(call, delegateMethod.ReturnType);
```
Comment (blairconrad) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: I would almost consider pulling `call = Expression.Assign(result, call)` from line 133 into this block, then having line 133 just becomes `bodyExpressions.Add(call)`, rather than having the reader re-evaluate the `isVoid`ness.

File: src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs (hunk 1 above)
Comment (thomaslevesque) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: I used `/* */` because Stylecop is a bit touchy about single-line comments:

> SA1512 : CSharp.Layout : A single-line comment must not be followed by a blank line. To ignore this error when commenting out a line of code, begin the comment with '////' rather than '//'.

But I can use `////` instead.

**Comment by blairconrad** [comment]
@thomaslevesque, looks good! I made some very minor controversial comments about code style, but really I'm content as things are.

File: src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs (hunk 2 above)
Comment (thomaslevesque) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: OK

File: src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs (hunk 3 above)
Comment (thomaslevesque) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: Good idea :+1:

File: src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs (hunk 1 above)
Comment (blairconrad) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: Oh. But that seems an abuse of `////` as well.
The problems is that you wanted

```c#
//     return result;
// }

bool isVoid = delegateMethod.ReturnType == typeof(void);
```

but StyleCop hated the line before `isVoid` and you don't like

```c#
//     return result;
// }
 bool isVoid = delegateMethod.ReturnType == typeof(void);
```

because it's too squished together?

I'm not wild about the squished up thing either.
I'm happy if you keep what you have, especially since I got around to opening the file alone and see that the block is indented. When I first looked at it, GitHub made me think it was left-aligned, which was probably the real "punch to the eye".

Comment (thomaslevesque) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: OK, I'll keep the `/* */` then

Comment (thomaslevesque) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: And remove the lines of `*` since they bother you ;)

Comment (blairconrad) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: Haha. Don't feel you have to. It was just the initial view I had:

image

that looked so weird. Seeing

image

is not so bad.

Comment (thomaslevesque) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: Too late :wink:

It would be nice to be able to use markdown in C# comments for better formatting...

**Comment by thomaslevesque** [comment]
Made a few changes in the implementation and added specs

Now rewriting existing specs to GWT style

**Comment by thomaslevesque** [comment]
> Now rewriting existing specs to GWT style

It seems to me that the existing specs in `AssignsOutAndRefParametersSpecs` don't make much sense... They all use a condition on the input value of an `out` parameter. But in C#, you can't read the value of an out parameter before you assign it, so it's not possible to get the initial value... It works only because the proxy uses generated code, which doesn't have this restriction. Unless you have a better idea, I'll change the parameter to `ref` so that it doesn't seem as weird.

File: src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs (hunk 1 above)
Comment (blairconrad) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: Surely there's an extension somewhere.

**Comment by thomaslevesque** [comment]
All done, I think

**Comment by thomaslevesque** [comment]
I'll squash the first 3 commits together, and leave the last one separate.

**Comment by thomaslevesque** [comment]
Oops, looks like I introduced a ton of code analysis violations... will fix ASAP

File: tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs [hunk 4]
```diff
@@ -2,122 +2,169 @@ namespace FakeItEasy.Specs
...
+        }
+
+        [Scenario]
+        public static void AssignOutAndRefParameterForNonVoidDelegate(
+            NonVoidDelegateWithOutAndRefParameters subject,
+            int refValue,
+            int outValue,
+            int result)
+        {
+            "Given a faked delegate with void return type and ref and out parameters"
```
Comment (blairconrad) [inline tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs]: not void

File: tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs [hunk 5]
```diff
@@ -2,122 +2,169 @@ namespace FakeItEasy.Specs
...
-                        string value = condition;
-                        subject.MightReturnAKnownValue(out value);
-                        value.Should().BeEquivalentTo(knownOutput);
-                    });
+                {
+                    outValue = Condition;
+                    subject.MightReturnAKnownValue(ref outValue);
+                });
+
+            "Then it should assign the conditional value to the ref field"
```
Comment (blairconrad) [inline tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs]: Based on recent comments in my property setter issue, I think @adamralph would push for something more like "Then is assigns the conditional value to the ref field". But he's not here.

**Comment by blairconrad** [comment]
Looks quite good to me, @thomaslevesque. Did note 1.5 small things up.
And it may not be to everyone's taste, but I did find the new version of the generator to be much more readable. Thanks.

File: tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs (hunk 4 above)
Comment (thomaslevesque) [inline tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs]: Nice catch! Copy/paste error...

File: tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs (hunk 5 above)
Comment (thomaslevesque) [inline tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs]: Since I'm at it, I might as well do it right. Will change it.

File: tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs [hunk 6]
```diff
@@ -2,122 +2,175 @@ namespace FakeItEasy.Specs
...
     {
-        [SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "0#", Justification = "Required for testing.")]
-        void MightReturnAKnownValue(out string andThisIsWhoReallyDidIt);
+        [SuppressMessage("Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId = "0#", Justification = "Required for testing.")]
+        void MightReturnAKnownValue(ref string andThisIsWhoReallyDidIt);
     }
 
     public static class AssignsOutAndRefParametersSpecs
     {
+        const string Condition = "someone_else";
```
Comment (blairconrad) [inline tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs]: Late-breaking comment. I don't think we have a test where we establish a condition and then don't meet it when exercising the subject. If we care about the ability to decide whether or not to assign the output, then maybe we should have an extra test. 
If we don't, the tests could become simpler...

Comment (thomaslevesque) [inline tests/FakeItEasy.Specs/AssignsOutAndRefParametersSpecs.cs]: Actually, I don't think the condition really matters. The out parameter *is* set to the `KnownOutput`, which proves that the lambda was executed; I think it's all that matters. And yes, the tests could be made simpler by removing the condition (and then I wouldn't have needed to change `out` to `ref`...)

**Comment by thomaslevesque** [comment]
@blairconrad I made the requested changes (except the one mentioned in https://github.com/FakeItEasy/FakeItEasy/pull/690#discussion_r61631099, but I'm not sure I should). I'll squash when I have your go.

**Comment by blairconrad** [comment]
@thomaslevesque, as we discussed off line, https://github.com/FakeItEasy/FakeItEasy/pull/690#discussion_r61631099 is out of scope and could be done later if we want.
Nice work. Squash it up!

**Comment by thomaslevesque** [comment]
Squashed

File: src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs [hunk 7]
```diff
@@ -74,24 +74,108 @@ private static Delegate CreateDelegateProxy(Type typeOfProxy, MethodInfo invokeM
...
+             * delegate void Foo(int x, ref int y, out int z);
+             *
+             * void ProxyFoo(int x, ref int y, out int z)
+             * {
+             *     var arguments = new[]{ (object)x, (object)y, (object)z };
+             *     eventRaiser.Raise(arguments);
+             *     y = (int)arguments[1];
+             *     z = (int)arguments[2];
+             * }
+             */
```
Comment (adamralph) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: I'm late to the game here, but I find this comment style a little odd. The leading `*` on each line seems redundant. I would expect

```C#
            /*
            Generate a method that:
            - wraps its arguments in an object array
            - passes this array to eventRaiser.Raise()
            ...
            */
```

or better still

```C#
            // Generate a method that:
            // - wraps its arguments in an object array
            // - passes this array to eventRaiser.Raise()
            ...
```

This would be consistent with other places where we have multi-line comments (I've never been a fan of `/* ... */` style comments):

* https://github.com/FakeItEasy/FakeItEasy/blob/3724e900b687981898f91d17c87c742568b5fce8/src/FakeItEasy/Core/FakeManager.EventRule.cs#L58-L62
* https://github.com/FakeItEasy/FakeItEasy/blob/3724e900b687981898f91d17c87c742568b5fce8/tests/FakeItEasy.Tests/Core/ArgumentConstraintTrapTests.cs#L68-L76

There are also quite a few 3 line comments and even plenty of 2 line comments, and they all use the `//` style.

Comment (adamralph) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: OK, so if the `//` style is used then StyleCop gives:

> SA1512 : CSharp.Layout : A single-line comment must not be followed by a blank line. To ignore this error when commenting out a line of code, begin the comment with '////' rather than '//'.

Perhaps `/*..*/` style is appropriate here. I do find the leading `*`s quite weird though. Is there any precedent for that style?

Comment (thomaslevesque) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: @adamralph, see the first comment thread (hidden - click "show comments" where it says "blairconrad and 1 other commented on an outdated diff") for the discussion about this.

Basically, if you have `//` comments followed by a blank line, StyleCop complains (because obviously, it knows better than us mere humans...). In the case of `Should_track_constraints_supplied_in_calls_made_from_overlapping_threads`, it works only because there's another comment after the blank line - if you remove it, it gives SA1512. That's why I used `/* */`. The alternatives are:

- use `////` instead of `//` (looks a bit weird)
- don't leave a blank line after the comment block (but it looks like it only applies to the next line)
- put another comment before the next line of code
- suppress the warning
- drop StyleCop :stuck_out_tongue:

Comment (thomaslevesque) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: > Perhaps /*..*/ style is appropriate here. I do find the leading *s quite weird though. Is there any precedent for that style?

Well, it must be pretty standard, because if you write a multiline `/* */` comment, Visual Studio automatically introduces the `*` on each new line (unless it's ReSharper?)

Comment (adamralph) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: @thomaslevesque it looks like our last comments crossed each other transit.

Comment (adamralph) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: It must be Resharper being "helpful". Vanilla VS doesn't insert `*`.

Comment (thomaslevesque) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: I've been using R# for so long that I don't even know what the normal VS behavior is :wink:

Comment (thomaslevesque) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: Now that I think of it, the comment could be outside the method, just above it. This way StyleCop won't complain, even with `//` comments.

Comment (adamralph) [inline src/FakeItEasy/Creation/DelegateProxies/DelegateProxyGenerator.cs]: Ah, of course! And that's probably where the comment does belong...

I did a few other minor refactorings while reading this file (also the older code, not just the latest changes) so I'll send a :lipstick: refactoring PR shortly...
