### PR TITLE
Automatic cancellation behavior

### LINKED ISSUE #904: Automatic cancellation support
I have a lot of dependencies with (usually `async`) methods that accept a `CancellationToken`. When the token is cancelled, these methods throw an `OperationCanceledException`. This is the expected implicit behavior for these methods, but by default, fakes don't throw anything when they receive a call with a cancelled token. So my thinking is that this behavior could be baked into FakeItEasy as a default rule. Currently I use a method like this:

```c#
private static void ConfigureCancellation(object obj)
{
    A.CallTo(obj)
        .WhenArgumentsMatch(args => args.OfType<CancellationToken>().Any(ct => ct.IsCancellationRequested))
        .Invokes(call => call.Arguments.OfType<CancellationToken>().FirstOrDefault(ct => ct.IsCancellationRequested).ThrowIfCancellationRequested());
}
```

It works fine, but I have to remember to call it on each fake.

Note that enabling this by default would, technically, be a breaking change, although probably not one that would affect many users.

### PR DESCRIPTION
**Pull request by thomaslevesque**
Fixes #904 

By default, calls that receive a cancelled `CancellationToken` argument will either:
- throw an `OperationCancelledException` (for synchronous methods)
- return a cancelled `Task` (for asynchronous methods)

This behavior will be overridden if the call is explicitly configured. To avoid this, the `CancellationToken` argument should be constrained to be not cancelled; a new `IsNotCancelled` extension method is provided as a shortcut for this scenario:

```
A.CallTo(() => foo.Bar(A<CancellationToken>.That.IsNotCancelled())).Returns(42);
```

A symmetric `IsCancelled` extension method is also available.

### CODE REVIEW

File: src/FakeItEasy/Core/FakeManager.CancellationRule.cs [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+    {
+#if FEATURE_BINARY_SERIALIZATION
+        [Serializable]
+#endif
+        private class CancellationRule : IFakeObjectCallRule
+        {
+            public int? NumberOfTimesToCall => null;
+
+            public bool IsApplicableTo(IFakeObjectCall fakeObjectCall) =>
+                fakeObjectCall.Arguments.OfType<CancellationToken>().Any(ct => ct.IsCancellationRequested);
```
Comment (thomaslevesque) [inline src/FakeItEasy/Core/FakeManager.CancellationRule.cs]: Oops, I just realized something... This will match any argument of type `CancellationToken`, *even if the parameter isn't declared as such* (e.g. if it's declared as `object`). I'll update it to take the actual parameter type into account.

File: src/FakeItEasy/Core/FakeManager.CancellationRule.cs [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+    {
+#if FEATURE_BINARY_SERIALIZATION
+        [Serializable]
+#endif
+        private class CancellationRule : IFakeObjectCallRule
+        {
+            public int? NumberOfTimesToCall => null;
+
+            public bool IsApplicableTo(IFakeObjectCall fakeObjectCall) =>
+                GetCancellationTokens(fakeObjectCall).Any();
```
Comment (blairconrad) [inline src/FakeItEasy/Core/FakeManager.CancellationRule.cs]: could the name of this method indicate that it's _cancelled_ cancellation tokens we're getting?

File: src/FakeItEasy/Core/FakeManager.cs [hunk 3]
```diff
@@ -45,6 +45,7 @@ internal FakeManager(Type fakeObjectType, object proxy)
                                          new CallRuleMetadata { Rule = new ObjectMemberRule(this) },
                                          new CallRuleMetadata { Rule = new AutoFakePropertyRule(this) },
                                          new CallRuleMetadata { Rule = new PropertySetterRule(this) },
+                                         new CallRuleMetadata { Rule = new CancellationRule() },
```
Comment (blairconrad) [inline src/FakeItEasy/Core/FakeManager.cs]: What if a property getter has a cancellation token as an argument? Do we want the property-ness behaviour to be preserved, or the cancellation behaviour?
I'd originally imagined the cancellation rule being first in the list.

File: src/FakeItEasy/TaskHelper.cs [hunk 4]
```diff
@@ -1,14 +1,59 @@
...
+
+        public static Task Cancelled<T>()
+        {
+            return Cancelled(typeof(T));
+        }
+
+        private static Task<T> CreateGenericCancelledTask<T>()
+        {
+            var source = new TaskCompletionSource<T>();
+            source.TrySetCanceled();
```
Comment (blairconrad) [inline src/FakeItEasy/TaskHelper.cs]: Is there any reason we'd expect this to return `false`? Equivalently, would `SetCanceled` be safe? I'd prefer it, unless there's a reason not to.

File: docs/default-fake-behavior.md [hunk 5]
```diff
@@ -22,11 +22,20 @@ invoked on the fake, no action will be taken by the fake. It is as if
...
+* otherwise, `default(T)` will be returned.
+
+### Cancellation tokens
+
+When a faked method that accepts a `CancellationToken` receives a cancelled token
+(i.e. with `IsCancellationRequested` set to `true`), it will either:
+
+* throw an `OperationCanceledException`, if it is synchronous;
+* return a cancelled task, if it is asynchronous (i.e. if it returns a `Task` or
+  `Task<T>`).
```
Comment (blairconrad) [inline docs/default-fake-behavior.md]: I'd consider reversing these. Then we can concentrate on the task/no task distinction and not worry about the synchronousness of the method (which we really can't determine from where we stand).

File: src/FakeItEasy/Core/FakeManager.CancellationRule.cs (hunk 2 above)
Comment (thomaslevesque) [inline src/FakeItEasy/Core/FakeManager.CancellationRule.cs]: Ah, yes. I intended to call it `GetCancelledTokens`, not sure why I didn't.

File: src/FakeItEasy/Core/FakeManager.cs (hunk 3 above)
Comment (thomaslevesque) [inline src/FakeItEasy/Core/FakeManager.cs]: My thinking was that it was very unlikely for a property to have a `CancellationToken` as an index, and if it did, it probably wouldn't mean what it usually means for a method, so I gave the `CancellationRule` a lower priority than the property rules. As for `ObjectMemberRules`, the members of `Object` don't accept cancellation tokens as argument, so there's no point in looking for them.

File: src/FakeItEasy/TaskHelper.cs (hunk 4 above)
Comment (thomaslevesque) [inline src/FakeItEasy/TaskHelper.cs]: You're right, `SetCanceled` has no reason to fail here. I was under the impression that `TrySetCanceled` was the "right" way to do it, because they added an overload with a `CancellationToken` in 4.6 for `TrySetCanceled` but not for `SetCanceled`. It doesn't matter in this case though, I'll change it to `SetCancelled`.

**Comment by thomaslevesque** [comment]
I pushed the requested changes

File: tests/FakeItEasy.Specs/CancellationSpecs.cs [hunk 6]
```diff
@@ -0,0 +1,240 @@
...
+    {
+        public interface IFoo
+        {
+            int Bar();
+
+            int Bar(CancellationToken cancellationToken);
+
+            int Bar(object obj);
+
+            Task<int> BarAsync(CancellationToken cancellationToken);
```
Comment (blairconrad) [inline tests/FakeItEasy.Specs/CancellationSpecs.cs]: I was expecting something with a plain `Task` too.

File: src/FakeItEasy/TaskHelper.cs [hunk 7]
```diff
@@ -1,14 +1,59 @@
 namespace FakeItEasy
 {
+    using System;
+    using System.Collections.Concurrent;
+    using System.Reflection;
     using System.Threading.Tasks;
 
     internal static class TaskHelper
     {
+        private static readonly Lazy<Task> CachedCancelledTask = new Lazy<Task>(CreateGenericCancelledTask<int>);
```
Comment (blairconrad) [inline src/FakeItEasy/TaskHelper.cs]: Could we instead use (or add) the value at `CachedCancelledTasks[typeof(int)]`?

File: src/FakeItEasy/TaskHelper.cs [hunk 8]
```diff
@@ -1,14 +1,59 @@
...
+            return CachedCancelledTasks.GetOrAdd(
+                resultType,
+                type =>
+                {
+                    var method = CreateGenericCancelledTaskGenericDefinition.MakeGenericMethod(type);
+                    return (Task)method.Invoke(null, new object[0]);
+                });
+        }
+
+        public static Task Cancelled<T>()
```
Comment (blairconrad) [inline src/FakeItEasy/TaskHelper.cs]: this is not used

File: src/FakeItEasy/TaskHelper.cs (hunk 7 above)
Comment (thomaslevesque) [inline src/FakeItEasy/TaskHelper.cs]: > Why int? Just because we need something and int is innocuous?

Yes.

> Could we instead use (or add) the value at `CachedCancelledTasks[typeof(int)]`?

Good point. Yes, we can totally do that.

File: tests/FakeItEasy.Specs/CancellationSpecs.cs (hunk 6 above)
Comment (thomaslevesque) [inline tests/FakeItEasy.Specs/CancellationSpecs.cs]: OK

File: tests/FakeItEasy.Specs/CancellationSpecs.cs [hunk 9]
```diff
@@ -0,0 +1,240 @@
...
+        {
+            "Given a fake"
+                .x(() => fake = A.Fake<IFoo>());
+
+            "When a method which doesn't accept a cancellation token is called"
+                .x(() => result = fake.Bar());
+
+            "Then it doesn't throw and returns the default value"
+                .x(() => result.Should().Be(0));
+        }
```
Comment (thomaslevesque) [inline tests/FakeItEasy.Specs/CancellationSpecs.cs]: Ah, yes, I thought you were talking about another one. I included it as a sanity check, but you're right, it's covered elsewhere. I'll remove it.

**Comment by thomaslevesque** [comment]
I made the requested changes. I'm not sure I'll be able to squash the last fixup commit cleanly, so if you don't mind, I think I'll squash all the specs commits together in the end.

File: tests/FakeItEasy.Specs/CancellationSpecs.cs [hunk 10]
```diff
@@ -149,7 +157,7 @@ public void AsyncNonCancelledCancellationToken(IFoo fake, CancellationToken canc
                 .x(() => cancellationToken = new CancellationToken(false));
 
             "When an async method is called with this cancellation token"
-                .x(() => task = fake.BarAsync(cancellationToken));
+                .x(() => { task = fake.BarAsync(cancellationToken); });
```
Comment (blairconrad) [inline tests/FakeItEasy.Specs/CancellationSpecs.cs]: Not a big deal, but what prompted this change (and its friends)?
It's a departure from many other of the one-line assignments in the file.

Comment (thomaslevesque) [inline tests/FakeItEasy.Specs/CancellationSpecs.cs]: Ah, yes, I intended to comment on it but I forgot. The `x` method has 2 overloads (4 actually, but we rarely use the ones with an `IStepContext`):
- one that takes an `Action`
- and one that takes a `Func<Task>`, for async scenarios

When I use

    .x(() => task = fake.BarAsync(cancellationToken))

the expression returns a task, so it's inferred to be a `Func<Task>`. And in that case, xBehave awaits the task. This is not what we want here (we just want to assign the task, not return it), so I use a statement body to force it to be inferred as `Action`. I had already noticed the problem for cancelled tasks because it caused the steps to fail, but I thought it would be more consistent to do the same for successful tasks.

Comment (thomaslevesque) [inline tests/FakeItEasy.Specs/CancellationSpecs.cs]: > It's a departure from many other of the one-line assignments in the file

True, but it's only necessary for task assignments.

**Comment by thomaslevesque** [comment]
Squashed. I also had to reorder the commits for things to make sense (otherwise I would have had specs that used `IsNotCancelled` before it was introduced).

**Comment by blairconrad** [comment]
> Ah, yes, I intended to comment on it but I forgot. The x method has 2 overloads (4 actually, but we rarely use the ones with an `IStepContext`):
>
> one that takes an Action
> and one that takes a `Func<Task>`, for async scenarios
> When I use
> 
> `.x(() => task = fake.BarAsync(cancellationToken))`
> the expression returns a task, so it's inferred to be a `Func<Task>`. And in that case, xBehave awaits the task. This is not what we want here (we just want to assign the task, not return it), so I use a statement body to
> force it to be inferred as Action. I had already noticed the problem for cancelled tasks because it caused the steps to fail, but I thought it would be more consistent to do the same for successful tasks.

Thanks! That helps!

I'll leave open for a bit in case @adamralph wants to peruse.

**Comment by adamralph** [comment]
I can peruse it later today if you don't mind waiting.

**Comment by thomaslevesque** [comment]
> I can peruse it later today if you don't mind waiting.

I don't mind at all :wink:

**Comment by thomaslevesque** [comment]
Thanks for the merge!
